"use client"

import { Github } from "lucide-react"

export function AboutSection() {
  return (
    <section className="max-w-3xl mx-auto px-4 py-16">
      <div className="rounded-2xl border border-gray-800 bg-gradient-to-br from-gray-900 to-gray-900/50 p-8 md:p-10">
        <p className="text-xs uppercase tracking-wider text-emerald-400 mb-3 font-medium">
          About this project
        </p>
        <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
          A hands-on exploration of image-to-image AI in a real product
          context.
        </h2>
        <p className="text-gray-400 leading-relaxed mb-6">
          Greenbloom is a portfolio project by{" "}
          <span className="text-white font-medium">Nivedita Patil</span>, built
          to probe what it takes to ship a visually-polished AI tool end-to-end
          — not just the model call, but the full stack around it: API cost
          control, abuse prevention, prompt engineering that survives contact
          with real users, and a UX that doesn&apos;t make them hunt for the
          Generate button.
        </p>
        <p className="text-gray-400 leading-relaxed mb-6">
          The redesigns you see are generated by FLUX.1 Kontext [pro] via
          fal.ai. The infrastructure is Next.js on Vercel, Upstash Redis for
          rate limiting, and Cloudflare Turnstile for bot protection. Full
          source and architecture notes on GitHub.
        </p>
        <a
          href="https://github.com/niveditapatil/greenbloom"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-gray-700 hover:border-emerald-500 hover:bg-gray-800 text-gray-300 hover:text-white text-sm font-medium transition-colors"
        >
          <Github className="h-4 w-4" />
          View on GitHub
        </a>
      </div>
    </section>
  )
}
